package engine

import (
	"bytes"
	"fmt"
	"os"
	"sort"
	"strconv"
	"strings"

	"github.com/UnitVectorY-Labs/gitrepoforge/internal/config"
	"gopkg.in/yaml.v3"
)

type managedFilesManifest struct {
	ManagedFiles []managedFileEntry `yaml:"managed_files"`
}

type managedFileEntry struct {
	Path       string               `yaml:"path"`
	Management string               `yaml:"management"`
	Sections   []managedSectionHint `yaml:"sections,omitempty"`
}

type managedSectionHint struct {
	Start string `yaml:"start"`
	End   string `yaml:"end"`
}

func renderManagedFilesManifest(data TemplateData, centralCfg *config.CentralConfig) (string, error) {
	entries := make([]managedFileEntry, 0, len(centralCfg.Files)+1)
	for _, rule := range centralCfg.Files {
		entry, ok, err := describeManagedFile(rule, data)
		if err != nil {
			return "", fmt.Errorf("describing managed file %s: %w", rule.Path, err)
		}
		if ok {
			entries = append(entries, entry)
		}
	}

	entries = append(entries, managedFileEntry{
		Path:       config.ManagedFilesManifestName,
		Management: "whole_file",
	})

	sort.Slice(entries, func(i, j int) bool {
		return entries[i].Path < entries[j].Path
	})

	body, err := yaml.Marshal(managedFilesManifest{
		ManagedFiles: entries,
	})
	if err != nil {
		return "", fmt.Errorf("marshal managed files manifest: %w", err)
	}
	if !bytes.HasSuffix(body, []byte("\n")) {
		body = append(body, '\n')
	}

	var out bytes.Buffer
	out.WriteString("# This file is generated by gitrepoforge.\n")
	out.WriteString("# Changes will be overwritten the next time gitrepoforge runs.\n")
	out.Write(body)
	return out.String(), nil
}

func describeManagedFile(rule config.FileRule, data TemplateData) (managedFileEntry, bool, error) {
	switch rule.Mode {
	case "", "create":
	case "delete":
		return managedFileEntry{}, false, nil
	default:
		return managedFileEntry{}, false, fmt.Errorf("unsupported mode %q", rule.Mode)
	}

	selected, err := selectTemplate(rule, data)
	if err != nil {
		return managedFileEntry{}, false, err
	}
	if selected.Absent {
		return managedFileEntry{}, false, nil
	}

	rawContent, err := os.ReadFile(selected.ResolvedPath)
	if err != nil {
		return managedFileEntry{}, false, fmt.Errorf("failed to read template %s: %w", selected.ResolvedPath, err)
	}

	parsed, err := parseTemplateDirectives(string(rawContent))
	if err != nil {
		return managedFileEntry{}, false, fmt.Errorf("parsing template directives: %w", err)
	}

	if parsed.IsWholeFile {
		return managedFileEntry{
			Path:       rule.Path,
			Management: "whole_file",
		}, true, nil
	}

	if len(parsed.Sections) == 0 {
		return managedFileEntry{}, false, nil
	}

	sections := make([]managedSectionHint, 0, len(parsed.Sections))
	for _, section := range parsed.Sections {
		sections = append(sections, managedSectionHint{
			Start: renderBoundaryHint(section.Start),
			End:   renderBoundaryHint(section.End),
		})
	}

	return managedFileEntry{
		Path:       rule.Path,
		Management: "sections",
		Sections:   sections,
	}, true, nil
}

func renderBoundaryHint(boundary Boundary) string {
	switch boundary.Type {
	case boundaryStartOfFile, boundaryEndOfFile:
		return boundary.Type
	case boundaryLine:
		return boundaryLine + "(" + boundary.Value + ")"
	case boundaryContent, boundaryContains:
		return boundary.Type + "(" + strconv.Quote(boundary.Value) + ")"
	default:
		if boundary.Value == "" {
			return boundary.Type
		}
		return boundary.Type + "(" + strconv.Quote(boundary.Value) + ")"
	}
}

func stripManagedFilesManifest(findings []Finding) []Finding {
	filtered := make([]Finding, 0, len(findings))
	for _, finding := range findings {
		if finding.FilePath == config.ManagedFilesManifestName {
			continue
		}
		filtered = append(filtered, finding)
	}
	return filtered
}

func managedFilesManifestFinding(findings []Finding) *Finding {
	for i := range findings {
		if findings[i].FilePath == config.ManagedFilesManifestName {
			return &findings[i]
		}
	}
	return nil
}

func managedFilePaths(entries []managedFileEntry) []string {
	paths := make([]string, 0, len(entries))
	for _, entry := range entries {
		paths = append(paths, entry.Path)
	}
	sort.Strings(paths)
	return paths
}

func parseManagedFilesManifest(content string) (managedFilesManifest, error) {
	trimmed := strings.TrimSpace(content)
	if trimmed == "" {
		return managedFilesManifest{}, nil
	}

	var manifest managedFilesManifest
	if err := yaml.Unmarshal([]byte(content), &manifest); err != nil {
		return managedFilesManifest{}, err
	}
	return manifest, nil
}
